version: "3"

services:
    app:
        container_name: docker-node-mongo
        restart: always
        build: .
        ports:
            - "80:2348"
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes: ./mongoDB:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: adminpass
